language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools


    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-26
